// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionAnimationsController from "./accordion_animations_controller"
application.register("accordion-animations", AccordionAnimationsController)

import FormController from "./form_controller"
application.register("form", FormController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PlanSelectController from "./plan_select_controller"
application.register("plan-select", PlanSelectController)

import PlanselectController from "./planselect_controller"
application.register("planselect", PlanselectController)

import ProjectsController from "./projects_controller"
application.register("projects", ProjectsController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ThankYouController from "./thank_you_controller"
application.register("thank-you", ThankYouController)
